export const MOCK_DATA = [
  { id: 'aaaa1', item: 'Alpha' },
  { id: 'bbbb1', item: 'Bravo' },
  { id: 'cccc1', item: 'Charlie' },
  { id: 'dddd1', item: 'Delta' },
  { id: 'eeee1', item: 'Echo' },
  { id: 'ffff1', item: 'Foxtrot' },
  { id: 'gggg1', item: 'Golf' },
  { id: 'hhhh1', item: 'Hotel' },
  { id: 'iiii1', item: 'India' },
  { id: 'jjjj1', item: 'Juliet' },
  { id: 'kkkk1', item: 'Kilo' },
  { id: 'llll1', item: 'Lima' },
  { id: 'mmmm1', item: 'Mike' },
  { id: 'nnnn1', item: 'November' },
  { id: 'oooo1', item: 'Oscar' },
  { id: 'pppp1', item: 'Papa' },
  { id: 'qqqq1', item: 'Quebec' },
  { id: 'rrrr1', item: 'Romeo' },
  { id: 'ssss1', item: 'Sierra' },
  { id: '2tttt1', item: 'Tango' },
  { id: 'uuuu1', item: 'Uniform' },
  { id: 'vvvv1', item: 'Victor' },
  { id: 'wwww1', item: 'Whiskey' },
  { id: 'xxxx1', item: 'X-ray' },
  { id: '1yyyy1', item: 'Yankee' },
  { id: 'zzzz1', item: 'Zulu' }
];
